### ISSUE TITLE
Please update egyptian national phone numbers

### ISSUE THREAD

**Issue by mohamedAdel01** [iamstevendao/vue-tel-input#244]
example of numbers 1116515445

it's consists of 10 number not 8

and thanks for this best package

**Comment by iamstevendao** [comment]
@mohamedAdel01 Can you update to the latest release and check if it works? Feel free to re-open the issue if not.
<img width="393" alt="Screen Shot 2021-07-04 at 16 21 23" src="https://user-images.githubusercontent.com/15044203/124375134-e1dd5d80-dce3-11eb-8e67-f330c89a0722.png">

**Comment by mohamedAdel01** [comment]
okay i will check it thank you

**Comment by georgeshokry** [comment]
Problem didn't fix, it doesn't validate the actual 10 characters in case of country is Egypt

**Comment by nooreldeensalah** [comment]
I can confirm this bug exists, and to elaborate further:
`+20 123 456 7891` is an example of a valid phone number, it consists of 10 digits (in addition to the country code).
This library considers a number to be valid if it consists of 8 digits (`+20 12345678`).

I'm not sure of the cause of this issue, but my initial guess would be it might be occurring when using the `international` mode because the number gets formatted due to `autoFormat` at `8` digits only when using the international mode, but it seems that other Vue libraries such as `vue-phone-number-input` suffer from the same issue.

I've tested a non-Vue related library `libphonenumber-js`, and it doesn't have this issue.
