### ISSUE TITLE
vue-tel-input@next is missing dropdownOptions.showSearchBox props

### ISSUE THREAD

**Issue by AndriiVakhula** [iamstevendao/vue-tel-input#397]
On vue-tel-input@next missing dropdownOptions.showSearchBox. And there is no way to search for the desired country

**Comment by mikhailkushkov** [comment]
HI folks, after update to vers. 8.1.0 (npm install vue-tel-input@latest), a 'showSearchBox' is still missing. In node modules -> vue-tel-input have only style.css (not vue-tel-input.css).
Any ideas ?

**Comment by iamstevendao** [comment]
thanks @Diarten. yep, it should be fixed in the latest (8.1.1).
sorry guys I have been migrating the build tool to `vite`, which created some hiccups. the documentation page is also updated using `vitepress`: https://vue-tel-input.iamstevendao.com/. I'll close it but feel free to reopen if it's still not working.

**Comment by Diarten** [comment]
@chinhdhse02750 do you use the vue-tel-input@next version?
I just use the latest version 8.1.1 (not  vue-tel-input@next ) with vue3 and it works well. 

`import VueTelInput from 'vue-tel-input';`
`import 'vue-tel-input/dist/vue-tel-input.css';`
`...`
`app.use(VueTelInput);`

https://vue-tel-input.iamstevendao.com/guide/installation.html
